spring:
  jpa:
    hibernate:
      ddl-auto: validate
    repositories:
      enabled: true
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/webify
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
upload:
  path: "/Users/a-shdv/IdeaProjects/uploads"
vaadin:
  urlMapping: /chat/*


