spring:
  jpa:
    hibernate:
      ddl-auto: update
    repositories:
      enabled: true
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/webify?serverTimezone=UTC
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
upload:
  path: "/Users/natalyashadaeva/IdeaProjects/uploads"