drop table if exists cart;
drop table if exists cart_item;
drop table if exists category;
drop table if exists "order";
drop table if exists order_info;
drop table if exists post;
drop table if exists product;
drop table if exists "user";
drop table if exists user_role;

create table cart
(
    id          int8 generated by default as identity,
    total_price float8,
    primary key (id)
);

create table cart_item
(
    id          int8 generated by default as identity,
    quantity    int4,
    total_price float8,
    cart_id     int8,
    product_id  int8,
    primary key (id)
);

create table category
(
    id    int8 generated by default as identity,
    image varchar(255),
    name  varchar(255),
    primary key (id)
);

create table "order"
(
    id               int8 generated by default as identity,
    city             varchar(255),
    comment          text,
    created_date     timestamp,
    email            varchar(255),
    name             varchar(255),
    phone_number     varchar(255),
    shipping_address varchar(255),
    status           int4,
    user_id          int8,
    primary key (id)
);

create table order_info
(
    id          int8 generated by default as identity,
    quantity    int4,
    total_price float8,
    order_id    int8,
    product_id  int8,
    primary key (id)
);

create table post
(
    id          int8 generated by default as identity,
    description varchar(255),
    header      varchar(255),
    user_id     int8,
    primary key (id)
);

create table product
(
    id          int8 generated by default as identity,
    description text,
    image       varchar(255),
    name        varchar(255),
    price       float8,
    category_id int8,
    primary key (id)
);

create table "user"
(
    id       int8 generated by default as identity,
    active   boolean,
    password varchar(255),
    username varchar(255),
    cart_id  int8,
    primary key (id)
);

create table user_role
(
    user_id       int8 not null,
    user_role_set varchar(255)
);

alter table if exists cart_item add constraint cart_item_cart foreign key (cart_id) references cart;
alter table if exists cart_item add constraint cart_item_product foreign key (product_id) references product;
alter table if exists "order" add constraint order_user foreign key (user_id) references "user";
alter table if exists order_info add constraint order_info_order foreign key (order_id) references "order";
alter table if exists order_info add constraint order_info_product foreign key (product_id) references product;
alter table if exists post add constraint post_user foreign key (user_id) references "user";
alter table if exists product add constraint product_category foreign key (category_id) references category;
alter table if exists "user" add constraint user_cart foreign key (cart_id) references cart;
alter table if exists user_role add constraint user_role_user foreign key (user_id) references "user";