DROP TABLE IF EXISTS cart CASCADE;
DROP TABLE IF EXISTS cart_product CASCADE;
DROP TABLE IF EXISTS category CASCADE;
DROP TABLE IF EXISTS "order" CASCADE;
DROP TABLE IF EXISTS order_product CASCADE;
DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;
DROP TABLE IF EXISTS user_role CASCADE;

CREATE TABLE cart
(
    id          INT8 GENERATED BY DEFAULT AS IDENTITY,
    total_price FLOAT8,
    PRIMARY KEY (id)
);

CREATE TABLE cart_product
(
    id         INT8 GENERATED BY DEFAULT AS IDENTITY,
    price      FLOAT8,
    quantity   INT4,
    cart_id    INT8,
    product_id INT8,
    PRIMARY KEY (id)
);

CREATE TABLE category
(
    id    INT8 GENERATED BY DEFAULT AS IDENTITY,
    image VARCHAR(255),
    name  VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE "order"
(
    id               INT8 GENERATED BY DEFAULT AS IDENTITY,
    apartment_number INT4,
    comment          TEXT,
    created_date     timestamp,
    door_password    INT,
    entrance_number  INT4,
    floor            INT4,
    shipping_address VARCHAR(255),
    user_id          INT8,
    PRIMARY KEY (id)
);

CREATE TABLE order_product
(
    id         INT8 GENERATED BY DEFAULT AS IDENTITY,
    price      FLOAT8,
    quantity   INT4,
    order_id   INT8,
    product_id INT8,
    PRIMARY KEY (id)
);

CREATE TABLE post
(
    id          INT8 GENERATED BY DEFAULT AS IDENTITY,
    description VARCHAR(255),
    header      VARCHAR(255),
    user_id     INT8,
    PRIMARY KEY (id)
);

CREATE TABLE product
(
    id          INT8 GENERATED BY DEFAULT AS IDENTITY,
    description TEXT,
    image       VARCHAR(255),
    name        VARCHAR(255),
    price       FLOAT8,
    category_id INT8,
    PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id       INT8 GENERATED BY DEFAULT AS IDENTITY,
    active   BOOLEAN,
    email    VARCHAR(255),
    password VARCHAR(255),
    phone    VARCHAR(255),
    username VARCHAR(255),
    cart_id  INT8,
    PRIMARY KEY (id)
);

CREATE TABLE user_role
(
    user_id       INT8 NOT NULL,
    user_role_set VARCHAR(255)
);

ALTER TABLE IF EXISTS cart_product
    ADD CONSTRAINT cart_product_cart FOREIGN KEY (cart_id) REFERENCES cart;

ALTER TABLE IF EXISTS cart_product
    ADD CONSTRAINT cart_product_product FOREIGN KEY(product_id) REFERENCES product;

ALTER TABLE IF EXISTS "order"
    ADD CONSTRAINT order_user FOREIGN KEY (user_id) REFERENCES "user";

ALTER TABLE IF EXISTS order_product
    ADD CONSTRAINT  order_product_order FOREIGN KEY (order_id) REFERENCES "order";

ALTER TABLE IF EXISTS order_product
    ADD CONSTRAINT  order_product_product FOREIGN KEY (product_id) REFERENCES product;

ALTER TABLE IF EXISTS post
    ADD CONSTRAINT  post_user FOREIGN KEY (user_id) REFERENCES "user";

ALTER TABLE IF EXISTS product
    ADD CONSTRAINT  product_category FOREIGN KEY (category_id) REFERENCES category;

ALTER TABLE IF EXISTS "user"
    ADD CONSTRAINT user_cart FOREIGN KEY (cart_id) REFERENCES cart;

ALTER TABLE IF EXISTS user_role
    ADD CONSTRAINT user_role_user FOREIGN KEY (user_id) REFERENCES "user";