insert into products (name, category_id, image, description, price)
values ('iPhone X 64GB', 1, '/images/products/iphone-x-64-gb.jpg', 'Отличный продвинутый телефон с памятью на 64 gb',
        71990),
       ('iPhone X 256GB', 1, '/images/products/iphone-x-256-gb.jpg', 'Отличный продвинутый телефон с памятью на 256 gb',
        89990),
       ('HTC One S', 1, '/images/products/htc-one-s.jpeg', 'Зачем платить за лишнее? Легендарный HTC One S', 12490),
       ('iPhone 5SE', 1, '/images/products/iphone-5-se.jpg', 'Отличный классический iPhone', 17221),
       ('Наушники Beats Audio', 2, '/images/products/beats-audio.jpg', 'Отличный звук от Dr. Dre', 20221),
       ('Камера GoPro', 2, '/images/products/go-pro.jpg', 'Снимай самые яркие моменты с помощью этой камеры', 12000),
       ('Камера Panasonic HC-V770', 2, '/images/products/panasonic.jpg',
        'Для серьёзной видео съемки нужна серьёзная камера. Panasonic HC-V770 для этих целей лучший выбор!', 27900),
       ('Кофемашина DeLonghi', 3, '/images/products/delonghi.jpg', 'Хорошее утро начинается с хорошего кофе!', 25200),
       ('Холодильник Haier', 3, '/images/products/haier.jpg', 'Для большой семьи большой холодильник!', 40200),
       ('Блендер Moulinex', 3, '/images/products/moulinex.jpg', 'Для самых смелых идей', 4200),
       ('Мясорубка Bosch', 3, '/images/products/bosch.jpg',
        'Любите домашние котлеты? Вам определенно стоит посмотреть на эту мясорубку!', 9200);